name: compile-check

on: [ push, pull_request ]

permissions: {}

jobs:
  compile:
    runs-on: windows-latest
    env:
      NS_MOD_DIR: "" # Change this to your mod directory example mods\\Nekos.Attrition.Extended.Recode or leave it empty if you use GreenTF thunderstore upload

    steps:
      - name: Checkout Repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: NorthstarMod
          persist-credentials: false

      - name: Checkout Northstar Mods
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: R2Northstar/NorthstarMods
          ref: main
          path: mods/
          persist-credentials: false

      - name: Copy Northstar Mod Into Mods
        run: |
          xcopy NorthstarMod\%NS_MOD_DIR% mods\NorthstarMod /E /I /Y

      - name: Compile Scripts
        uses: ASpoonPlaysGames/squirrel-re-compiler@d1f094852c8d8e6fdf49b26b7b74f119bb5731a0 # v3.0.4
        with:
          mods-directory: "${{ github.workspace }}/mods"
          native-json: "${{ github.workspace }}/NorthstarMod/.github/natives.json"
          vanilla: false
