name: compile-check

on: [ push, pull_request ]

permissions: {}

jobs:
  compile:
    runs-on: windows-latest
    env:
      NS_MOD_DIR: "" # Change this to your mod directory example mods\\Nekos.Attrition.Extended.Recode or leave it empty if you use GreenTF thunderstore upload

    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: NorthstarMod
          persist-credentials: false

      - name: Checkout Northstar Mods
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: R2Northstar/NorthstarMods
          ref: main
          path: mods/
          persist-credentials: false

      - name: Copy Northstar Mod Into Mods
        run: |
          $SourcePath = Join-Path "NorthstarMod" "$env:NS_MOD_DIR"
          New-Item -ItemType Directory -Force -Path "mods\NorthstarMod"
          Copy-Item -Path "$SourcePath\*" -Destination "mods\NorthstarMod" -Recurse -Force

      - name: Compile Scripts
        uses: ASpoonPlaysGames/squirrel-re-compiler@d1f094852c8d8e6fdf49b26b7b74f119bb5731a0 # v3.0.4
        with:
          mods-directory: "${{ github.workspace }}/mods"
          native-json: "${{ github.workspace }}/mods/.github/natives.json"
          vanilla: false
