name: Check Formatting

on: [ push, pull_request ]

permissions: {}

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Download sqformat
        run: |
          curl -sSL https://github.com/Bobbyperson/sqformat/releases/download/v1.2.0/sqformat-linux-x86_64 -o sqformat
          echo "d584cb738c3fa3fa467d64e5bd009a4819284b4fca18864697a7904ed2b3d253bdd026b23cc4baccd4e59f4562a1c4ef59fcbe3a525d3d3dbc261cd2566603a3  sqformat" | sha512sum -c -
          chmod +x sqformat

      - name: Check formatting
        run: ./sqformat -dr .
