name: Check Formatting

on: [ push, pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Download sqformat
        run: |
          curl -sSL https://github.com/Bobbyperson/sqformat/releases/download/v1.2.0/sqformat-linux-x86_64 -o sqformat
          chmod +x sqformat

      - name: Check formatting
        run: ./sqformat -dr .
